---
- name: Check if Debian
  include: "install.deb.yml"
  when: ansible_os_family == 'Debian'

- name: create django dir
  file:
    path: "{{ django_path }}"
    state: directory
    mode: 0660
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
  register: init

- name: install django
  pip:
    name:
      - django
    virtualenv: "{{ django_path }}/djangoenv"
    virtualenv_command: /usr/bin/python3.6 -m venv
    chdir: "{{ django_path }}"
  become_user: "{{ apache_user }}"

- name: check manage permissions
  file:
    path: "{{ django_path }}/manage.py"
    state: file
    mode: 0766
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
  register: init

- name: init django project
  command: django-admin startproject djangoproject .
  args:
    chdir: "{{ django_path }}"
  when: init.changed
  become_user: "{{ apache_user }}"

- name: init django database
  django_manage:
    command: migrate
    app_path: "{{ django_path }}"
    virtualenv: "{{ django_path }}/djangoenv"
  become_user: "{{ apache_user }}"

- name: add django admin
  command: "echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'pass')\" | {{ django_path }}/djangoenv/bin/python djangoproject/manage.py shell"
  chdir: "{{ django_path }}"
  when: init.changed
  become_user: "{{ apache_user }}"

- name: add settings.py
  template:
   src: settings.py.j2
   dest: "{{ django_path }}/djangoproject/settings.py"
   owner: "{{ apache_user }}"
   group: "{{ apache_group }}"
   mode: 0600
