---
- name: Check if Debian
  include: "install.deb.yml"
  when: ansible_os_family == 'Debian'

# python3.6 -m venv my_env
# source my_env/bin/activate
# pip install django
# django-admin startproject djangoproject .
# python manage.py migrate
# echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'pass')" | python manage.py shell

- name: add settings.py
  template:
   src: settings.py.j2
   dest: /var/www/django/djangoproject/settings.py
   owner: root
   group: root
   mode: 0600
